### PR TITLE
[approval-request] added myself to Current Project Members

### PR DESCRIPTION
**Pull request by LizHareDogs**
### Summary

Add myself to the bottom of the "Current Project Members" section.

### List of changes proposed in this PR (pull-request)

Added the following line:

| Liz Hare | <br>([@LizHareDogs](https://github.com/LizHareDogs)) | Dog Genetics LLC | The Turing Way Accessibility Co-Lead | 2023 - Present | - |

### What should a reviewer concentrate their feedback on?

Just that line :)

- [X ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by aleesteele** [comment]
Looks great! Thanks @LizHareDogs :)

**Review by aleesteele — APPROVED** [review]
Approved 🚀

**Comment by LizHareDogs** [comment]
Hi Anne,

I went to merge this and GitHub says"

"Only those with write access to this repository can merge pull requests. I know I've been able to do this before so it might have something to do with the transition to the TTW organization on GH.

Please let me know what you'd like me to do!


Liz Hare, PhD
Dog Genetics LLC
***@***.***
http://www.doggenetics.com <http://www.doggenetics.com/>

**Comment by da5nsy** [comment]
Hi @LizHareDogs!
I've just added you as a collaborator with write access, so you should be able to go ahead and merge now.
I'm curious as to why those permissions didn't get automatically transferred over - they should've been. I'll make a note of this in the infrastructure Slack channel, just to make a record of it in case it's an indicator of some underlying problem we should be attending to. 
@the-turing-way/infrastructure

**Pull request merged**
