### PR TITLE
Move workshop documents to new repositories

### PR DESCRIPTION
**Pull request by JimMadge**
### Summary

Contributes to #3352 

Move workshops directories to new repos,

- [book dash](https://github.com/the-turing-way/book-dash)
- [Boost Your Research Reproducibility with Binder](https://github.com/the-turing-way/boost-research-reproducibility-binder)
- [Build a BinderHub](https://github.com/the-turing-way/build-a-BinderHub)
- [others](https://github.com/the-turing-way/workshops)

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by bsipocz — CHANGES_REQUESTED** [review]
the collabw19 and github workshops have not been moved, so I would hold up this PR until those are sorted. I don't necessarily advocate for separate workshop repos for those, though they could be separated out.

**Comment by JimMadge** [comment]
> the collabw19 and github workshops have not been moved, so I would hold up this PR until those are sorted. I don't necessarily advocate for separate workshop repos for those, though they could be separated out.

Yeah, I wasn't certain about those. They feel more like an archive of meeting notes, a lot of which are only a list of name.

@KirstieJane do you have a strong opinion on if/where those should be archived?

**Comment by bsipocz** [comment]
Yes, fair enough, but they still need to go somewhere before being deleted.

The easy workaround would be if you could remove those not yet migrated directories from this PR, so we can go ahead merge the easy parts fast.

**Comment by JimMadge** [comment]
> Yes, fair enough, but they still need to go somewhere before being deleted.
> 
> The easy workaround would be if you could remove those not yet migrated directories from this PR, so we can go ahead merge the easy parts fast.

Good idea, I'll do that :+1:.

**Comment by JimMadge** [comment]
Actually, I think I _will_ move them from here, but also create a workshops repo. To keep this repo clean and avoid more workshops being added here in the meantime.

**Review by bsipocz — APPROVED** [review]
Looks all good.

**Comment by bsipocz** [comment]
Thanks @JimMadge for driving this cleanup!

**Pull request merged**
