### PR TITLE
[Ready for review] Fix small typos in the Community Handbook

### LINKED ISSUE #3346: [TO EDIT] community-handbook fixing minor typos
### Summary

While reading through the Community Handbook I'm discovering a few very minor but otherwise (I think) uncontroversial typos. For examples:
1. On the [local-build.md](https://the-turing-way.netlify.app/community-handbook/local-build) page there is a missing bracket in the first paragraph that breaks the Jupyter Book link.
2. On the [coc-enformcement.md](https://the-turing-way.netlify.app/community-handbook/coc/coc-enforcement) page, "about someone is the committee" should be "about someone on the committee".
3. On the [style-crossref.md](https://the-turing-way.netlify.app/community-handbook/style/style-crossref) page, "placeholder for subchapter's name" should be "placeholder for the subchapter's name".

These are all minor things, but look easy to fix, and I'm hoping also an easy way for me to make my first pull request and understand the processes involved.

### What needs to be done?

The proposed change would leave the structure as it is but just make minor changes to the wording, alongside small changes to syntax and punctuation.

### Who can help?

Checking the git history it looks like at least @malvikasharan and @arronlacey were involved withe the writing of the relevant chapters.

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

### PR DESCRIPTION
**Pull request by llewelld**
### Summary

Fixes #3346

These are very minor and hopefully relatively uncontroversial fixes, mostly for typos, in the Community Handbook sections.

### List of changes proposed in this PR (pull-request)

* Multiple very minor typos.
* None of the changes are more than a couple of words.
* None of the changes should be controversial, but if any are, that's likely a misunderstanding on my part and I can just drop the problematic ones.

### What should a reviewer concentrate their feedback on?

- [ ] The changes are small enough to be considered typos.
- [ ] The changes make sense.
- [ ] All of the changes are uncontroversial.

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by kallewesterling — APPROVED** [review]
I've read through the changes that @llewelld has made in this PR, and it looks good.

**Review by aleesteele — APPROVED** [review]
Looks great! This is a fantastic way to kick off Book Dash week, @llewelld! Thanks for the review 🙏

**Comment by llewelld** [comment]
@kallewesterling; @aleesteele, thank you both for your incredible responsiveness in checking this, and for your encouragement :smile:

**Comment by llewelld** [comment]
@all-contributors please add @llewelld for bug

**Pull request merged**
