### PR TITLE
[ready for merge] co-working call notes from july, august, september

### PR DESCRIPTION
**Pull request by aleesteele**
### Summary

- Ongoing notes from july, august, september, october

### CODE REVIEW

**Review by eirini-zormpa — APPROVED** [review]
looks good in general - is adding people's full names okay though?

**Comment by aleesteele** [comment]
Great point @eirini-zormpa! I'll post this to the core team channel on slack to ask what folks think, as well as pull in @AlexandraAAJ, @malvikasharan, @KirstieJane and @Arielle-Bennett from the staff delivery team here for their comments. Really important point re: the need to protect people's privacy when archiving public notes.

Also @Davsarper - you might be the go-to-guy for GDPR knowledge from TPS more broadly, any thoughts here?

For context, we have been archiving our notes for the coworking calls in recent months in a newly created 'governance' folder, and Eirini is flagging the privacy implications of doing so, as Github's servers are not based in the UK, so technically the storage of people's information on Github is an international data transfer.

Flagging that this is also being discussed or flagged in the wider Github community here: https://github.com/orgs/community/discussions/63197

**Comment by Davsarper** [comment]
Hi, go-to guy here. I believe that if GH servers are in the USA the key thing is that they have named representatives in the UK/Europe as they handle data, the international data transfer would be within reason to provide the service. If needed I can look a little deeper and verify what I am saying.

In any case I would consider wheter keeping names in a public place is necessary at all, if it is not then better keep them out.
Also if we are storing any personal data we would need to make people aware in meeting about what we store, where, for what and for how long. There should also be a way for them to exercise their rights at any point.

**Comment by aleesteele** [comment]
added notes for 14 & 21 august (none for 28 august due to bank holiday)

**Comment by aleesteele** [comment]
adding in notes here from end of September and October - also flagging here that at co-working this week, @KirstieJane and others discussed data protection policies within the Turing and how they apply within TTW. flagging this PR for @malvikasharan and @AlexandraAAJ as well as we review how we archive public notes within the project! 😄

**Comment by AlexandraAAJ** [comment]
Thanks Anne, with regards to GDPR, I would like to suggest to add a note in our Collab Cafe and coworking documents.
**"The information provided in this etherpad/hackmd, including the names of participants will be uploaded in our Github repository (add the folder name) to allow other community members to review the discussion topics, outputs and actions. Please feel free to use a pseudonym if you don't feel comfortable sharing your name"**

I could take this wording/phrasing, or other suggestion to the GDPR drop-in session next week.

**Review by malvikasharan — APPROVED** [review]

**Comment by aleesteele** [comment]
_Adding breadcrumbs here to #3534_

**Pull request merged**
