### PR TITLE
Update code-styling-guidelines.md

### PR DESCRIPTION
**Pull request by Cghlewis**
Update broken link

### Summary

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by Cghlewis** [comment]
I also have a chapter on developing Style Guides in case that's a useful resource to link to: https://datamgmtinedresearch.com/style

**Review by da5nsy — APPROVED** [review]

**Comment by KirstieJane** [comment]
Please do add in your link too @Cghlewis! Approved and ready to merge if you'd like to do that in another PR though 🙏

**Comment by Cghlewis** [comment]
> Just sent you an invite to join the community so you can click the green merge button yourself ✅

I accepted your invite and tried to merge in this change but it says I don't have write access.

**Comment by KirstieJane** [comment]
Hmmmm - I just did something in the settings - can you try again?

(This is for sure my lack of understanding and trying to do things on my phone 😅)

If it doesn't work again I'll return on Monday on my laptop!

**Comment by da5nsy** [comment]
I've nipped in and given @Cghlewis write access 👍 
Should work now!

**Comment by KirstieJane** [comment]
Thank you @da5nsy! 🌻🌸🌺

**Comment by Cghlewis** [comment]
> Thank you @da5nsy! 🌻🌸🌺

Thanks, all!

**Pull request merged**
