### PR TITLE
Adding Slack policy to community handbook

### LINKED ISSUE #3233: Add Slack guide in the community handbook
### Summary

Governance-related actions on different committees, working groups and core delivery team
Find details in #3215 

### What needs to be done?

**Add Slack guide in the community handbook**  -- assign to the Community Manager, involve community members

- How long is too long to leave a post unanswered in TTW Slack
    - We have a Slack Guide - not sure if we do need to go into such granular detail. Ideally, CM and other community members keep an eye on the posts.
- slack is a lot - important messages can be lost quickly (many people are in multiple workspaces)
    - Update the Slack guide - add Slack guide in the Community handbook

### Who can help?

- @aleesteele add and also invite community consultation

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### PR DESCRIPTION
**Pull request by aleesteele**
### Summary

Will close #3233. Adding now to use preview feature.

- Creates new section in communication handbook on community platforms
- Adds specific section for slack policy from this HackMD: https://hackmd.io/@turingway/ttw-slack-intro
- Adds quick start guide: https://hackmd.io/LuP1kxxYTNmGiM2rPElVlg

### CODE REVIEW

**Comment by aleesteele** [comment]
Added a small landing page - and also used this as an pportunity to upload the 'quick start guide' for slack!

**Review by AlexandraAAJ — COMMENTED** [review]
Thanks Anne, I found this super helpful. No reviews to add.

**Comment by aleesteele** [comment]
Thank you @AlexandraAAJ! Would you be able to approve this PR so that we can merge it? Thank you!! 😄

**Review by AlexandraAAJ — APPROVED** [review]

**Comment by aleesteele** [comment]
Oh no - just tried to search for the policy, and saw that it doesn't appear in the menu page. Will make a new PR.

**Pull request merged**
