### PR TITLE
Update Slack link

### PR DESCRIPTION
**Pull request by da5nsy**
Re: https://github.com/the-turing-way/the-turing-way/issues/3961

### CODE REVIEW

**Comment by aleesteele** [comment]
@da5nsy - thank you for making this PR! Could you switch this out with https://tinyurl.com/jointuringwayslack?

**Review by aleesteele — CHANGES_REQUESTED** [review]
Request to change urls to https://tinyurl.com/jointuringwayslack

**Comment by da5nsy** [comment]
We could theoretically set up a redirect ourselves for the joining link.
We currently have one (http://slack.the-turing-way.org/) for the Slack itself, but my understanding is that that link only works if you're a member already, so we'd need a seperate one (is that right @JimMadge ?)

**Comment by JimMadge** [comment]
`slack.the-turing-way.org` includes the invitation key so I think that should work.

**Comment by JimMadge** [comment]
I would also support moving away from third party link shorteners, the Google service recently closed and I think others insert tracking.

**Review by malvikasharan — APPROVED** [review]
Thank you @da5nsy. 🎉

**Comment by malvikasharan** [comment]
@JimMadge - do you mean we should not use bit.ly or tinylink kinds of services especially to add links in our book?

**Comment by da5nsy** [comment]
> slack.the-turing-way.org

Oh great - so we can use that in both the "click here to sign up" and the "click here to use slack" contexts?

**Comment by bsipocz** [comment]
> do you mean we should not use bit.ly or tinylink kinds of services especially to add links in our book?

In the book we can render a link under any text, so I would suggest not to use these shorteners at all. IMO their usage should be limited to the case where you expect the reader to type in the URL themselves rather than clicking though links. Or maybe in basic text emails where a very long string is not reader friendly.

**Comment by JimMadge** [comment]
Agreed with @bsipocz, but also because it introduces a reliance on third party services which might disappear or align poorly with our values.

**Comment by JimMadge** [comment]
> Completely agreed. We can capture that in the style guide. Thank you all.

Issue here https://github.com/the-turing-way/the-turing-way/issues/3988

**Review by aleesteele — APPROVED** [review]
Totally makes sense - I stand 100% corrected - thanks for making the issue @JimMadge and for the correction in the guides @da5nsy and further context @bsipocz :) Good to know for future presentations too!

**Comment by bsipocz** [comment]
I was just thinking about emails, but you're right, presentations are a good place for these shorter links, too. 

However I'm becoming a qr code fan myself for links in presentations, but I don't know if they are better or worse for accessibility.

**Review by bsipocz — APPROVED** [review]

**Pull request merged**
