### PR TITLE
Move project management documents

### PR DESCRIPTION
**Pull request by JimMadge**
### Summary

Contributes to #3352 

Move project management directory to a [new repo](https://github.com/the-turing-way/project-management)

~~The following directories were "soft deleted" (`git rm -r`, but they are still in the history so no data has been lost)~~

- ~~archive~~
- ~~credit requests~~
- ~~legacy documents~~

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by bsipocz — CHANGES_REQUESTED** [review]
I don't see come of these directories in the other repo (e.g. archive). Has the migration finished or were those decided not to be included? 

I'm OK with either way, and just want to make sure it's not accidental deletion here, thus I change this to "request for changes"; it's more like a "request for clarification"

**Comment by JimMadge** [comment]
> I don't see come of these directories in the other repo (e.g. archive). Has the migration finished or were those decided not to be included?
> 
> I'm OK with either way, and just want to make sure it's not accidental deletion here, thus I change this to "request for changes"; it's more like a "request for clarification"

Yes I deleted those _after_ the `git filter-repo`, so they are still in the history of the new repo. I did that because those directories seemed to explicitly hold information that was old and likely not needed any more.

**Comment by KirstieJane** [comment]
@JimMadge - can you ping me on slack to just talk through this point about the archive folder? I'm not sure I'm totally following...

**Comment by JimMadge** [comment]
The decision is to keep all files/directories _except_ for any duplicates.

**Comment by KirstieJane** [comment]
Yes - thank you!

These are old files but they're very useful for telling the story of the Turing Way so far 🙏

**Comment by JimMadge** [comment]
Ok, files restored and duplicates removed at the [new repo](https://github.com/the-turing-way/project-management).

Are you happy to approve @KirstieJane ?

**Review by bsipocz — APPROVED** [review]
OK, this now looks good. Thanks!

**Comment by bsipocz** [comment]
Thanks @JimMadge!

**Pull request merged**
