### PR TITLE
Update profiles.yml

### PR DESCRIPTION
**Pull request by Preshh0**
### Summary

This PR contains a new path way on Multinational Collaboration.

The aim is to guide projects/initiatives that would include collaboration across various nations (countries).

### List of changes proposed in this PR (pull-request)

* Adding a new pathway. 

### What should a reviewer concentrate their feedback on?

- [ ] Do the chapters suggested fall in line with the intent of the pathway?
- [ ] Does the description convey the intent of the pathway named?
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:  Tagging @JimMadge for a review.

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
There were a few linting/style errors in the YAML file but it looks good to me. You can check the deploy preview to see if it has curated the chapters like you wanted :+1:.

**Comment by Preshh0** [comment]
Hi @JimMadge, thank you!

I am seeing in the preview that the order is not as it was written in the PR. Is there a way to fix this?

**Comment by JimMadge** [comment]
It looks like the chapters are listed in the same order as the ToC.

I don't think there is any way to change that now. It would have to be a feature request [here](https://github.com/the-turing-way/pathways).

**Comment by Preshh0** [comment]
Alright. I have raised on [here](https://github.com/the-turing-way/pathways/issues/16).

**Review by malvikasharan — APPROVED** [review]
Looks good to me. Thank you @Preshh0 and @JimMadge. 🎉

**Pull request merged**
