### PR TITLE
[ready for merge] Fix broken link

### PR DESCRIPTION
**Pull request by hanneoberman**
### Summary

Edited one link. The shields.io website has been updated and analysis badges no longer have their own link.

Fixes #NA

### List of changes proposed in this PR (pull-request)

* Just the one link

### What should a reviewer concentrate their feedback on?

NA

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thank you so much @hanneoberman. 🎉 Really appreciate you taking the time to edit.

**Review by EKaroune — APPROVED** [review]
thanks for this bug fix

**Comment by hanneoberman** [comment]
@Arielle-Bennett I have updated my fork, but I do not have write access to merge the PR

**Comment by Arielle-Bennett** [comment]
@hanneoberman I've added you as a contributor so you should be able to go ahead and merge this and the other PR you opened :tada:

**Pull request merged**
