### PR TITLE
BUG: use absolute links to avoid rendering error

### LINKED ISSUE #3976: [BUG] CI: build fails with myst reference issue
The top level markdown files use simple references to other markdown files. However, these started to cause CI build issues, even though the files are not part of the book, thus shouldn't go through the rendering.
On github all the links resolve correctly.

I would suggest adding these top level markdowns to the ignore list?

Failing example: the CoC links in https://github.com/the-turing-way/the-turing-way/blob/main/CONTRIBUTING.md

build log example:
https://github.com/the-turing-way/the-turing-way/actions/runs/12172154648/job/33950334696#step:5:924

### PR DESCRIPTION
**Pull request by bsipocz**
this should close #3976

### CODE REVIEW

**Review by JimMadge — APPROVED** [review]
It might be a bit confusing why absolute URLs are needed here if you don't realise this file is included in the book. I think this is the right fix though and CI should catch problems with the build tests :+1:.

**Comment by bsipocz** [comment]
First I thought the infrastructure is broken and we needed to add them to the ignore list, but as they are now rendered in (as of yesterday) we indeed need to run the link checker on them otherwise we can end up with broken links in the website.

 So please remove the commit you added.

**Comment by bsipocz** [comment]
(never mind, the commit can stay, but it's totally superfluous. Basically the pr that broke it had red CI prior merging too, so everything worked as expected )

**Comment by JimMadge** [comment]
> (never mind, the commit can stay, but it's totally superfluous. Basically the pr that broke it had red CI prior merging too, so everything worked as expected )

Yeah, I think that was because that PR changed files in the book directory as well as the Markdown files in the repository route. But here the CI workflow didn't run because _only_ the top-level Markdown files were edited. So, I think it would be possible for someone to edit those files and inadvertently break the build.

Probably not very likely but I thought it was worth trying to catch :smile:.

**Comment by JimMadge** [comment]
@bsipocz happy to merge?

**Comment by bsipocz** [comment]
Ah, I didn't check on if CI has run, just run the build locally to check this is enough of a fix. 

That being said, the workflow should have run after your commit though. So something is still not right?

**Comment by JimMadge** [comment]
I think it has run now, after that commit https://github.com/the-turing-way/the-turing-way/actions/runs/12181086675

**Comment by bsipocz** [comment]
> I think it has run now, after that commit https://github.com/the-turing-way/the-turing-way/actions/runs/12181086675

I should get up properly and start the day rather than using my phone for GitHub 😅

**Pull request merged**
