### PR TITLE
Editing and error fixing in the Foreword section

### PR DESCRIPTION
**Pull request by malvikasharan**
I noticed some errors in Foreword that this PR addresses.

Also fixes, some errors in recently merged files.
- Cae study: Practitioners Hub
- Afterword: Data statement

Original PR first opened 3 years ago 😅 #2033

### CODE REVIEW

**Review by BrainonSilicon — APPROVED** [review]
Looks great to me @malvikasharan 🚀

**Comment by malvikasharan** [comment]
Thank you Sophia. Please do add your phrasing suggestions here if you have some time. You can also open a new PR later. The showcase is tomorrow, so I will merge this tomorrow.

**Review by AlexandraAAJ — APPROVED** [review]
I've done tiny changes to the document

**Comment by malvikasharan** [comment]
Thank you Ale.

**Pull request merged**
