### PR TITLE
[WIP] testing sphinx panels

### PR DESCRIPTION
**Pull request by da5nsy**
### Summary

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
Neat! I saw this in Jupyter book only this week and was thinking of trying it for different guides. Really delighted to see that you are ahead of me. 🙌

**Comment by da5nsy** [comment]
@malvikasharan I was wondering if we might be able to hack it into a gallery but it doesn't look like it would be the best way

**Comment by malvikasharan** [comment]
I was looking at [this](https://jupyterbook.org/intro.html#find-the-right-documentation-resources) in the context of visualising curated sets of chapters (persona-wise) or giving different entry points in the book.

Did not think about the gallery view of images - in principle that should be work. Should we try automatically generating them by pulling images from the figures folder?

**Comment by da5nsy** [comment]
> Should we try automatically generating them by pulling images from the figures folder?

I do not know how to do that but please do feel free to take over this branch and play around :)

**Pull request closed without merging**
