### PR TITLE
Add new book dash June 24 contributions

### PR DESCRIPTION
**Pull request by mishkanemes**
- @mishkanemes: add new types of contribution
- @denisebianco: add a a new contributor

### CODE REVIEW

**Comment by aleesteele** [comment]
@all-contributors please add @mishkanemes for event organising

**Comment by aleesteele** [comment]
@all-contributors please add @denisebianco for event organising

**Review by aleesteele — CHANGES_REQUESTED** [review]
Undoing my previous approval - will explain in the comment

**Comment by aleesteele** [comment]
Hi @mishkanemes - I was just with discussing with @denisebianco about the process of adding contributors - and it's something that we automate rather than edit directly. You can do so using the syntax above, tagging @all-contributors - making sure to add each one at a time: https://github.com/the-turing-way/the-turing-way/blob/main/CONTRIBUTING.md#recognising-contributions

**Review by bsipocz — APPROVED** [review]
Given there is a fix to the name, too, I just go ahead and merge this PR rather than trigger the bot to open a new one with the contribution addition and then clean up a conflict here for adding the name fix.

**Comment by bsipocz** [comment]
Thanks @mishkanemes for your contributions!

**Pull request merged**
