### PR TITLE
[ready for merge] Fix names of 2 anchors in links.

### LINKED ISSUE #3464: Link gives 404 (Issue on page /communication/citable/citable-cite.html)
The [link](https://guide.esciencecenter.nl/#/citable_software/making_software_citable) about "adding a zenodo.json file" gives a 404 error.

Full link:
https://guide.esciencecenter.nl/#/citable_software/making_software_citable

Relevant line of markdown code here:
https://github.com/the-turing-way/the-turing-way/blob/46d74abec537a6c27f3699b46a25e60110710ecd/book/website/communication/citable/citable-cite.md?plain=1#L65

### PR DESCRIPTION
**Pull request by zimolzak**
### Summary

1. An external link in `citable-cite.md` was broken. Fixes #3464 

2. Two (anchor) links in the table of contents for `CONTRIBUTING.md` were broken. Probably due to markdown within the subsection titles themselves (and/or subsection titles getting renamed over time). I found this incidentally & did not open a separate issue for it. Just fixed it directly. Hope this is OK. This is my 1st pull request here! Strangely, while reading about how to submit a PR, I found a bug in the documentation about how to submit a PR :)

### List of changes proposed in this PR (pull-request)

* Copied and adapted some content (about making a `.zenodo.json` file) from the GitLab section to the GitHub section. I also updated the style of the filename `CITATION.cff` to be always upper case, consistent with the rest of the guide.
* Fix link to step 2 anchor in the TOC
* Fix link to step 4 anchor in the TOC

### What should a reviewer concentrate their feedback on?

- [ ] Look at the `citable-cite.md` page, GitHub tab, and review the content about making `.zenodo.json`
- [ ] Look at `CONTRIBUTING.md`. Test step 2 link in the TOC ("Fork _The Turing Way_ repository")
- [ ] Look at `CONTRIBUTING.md`. Test step 4 link in the TOC ("Submit a pull request")
- [ ] Consider testing the other TOC links in that file, to make sure no additional ones are broken (I tested them already, but maybe double check?)

### Acknowledging contributors

- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file: zimolzak

### CODE REVIEW

**Comment by zimolzak** [comment]
Uh oh, I meant to open up a separate PR for a separate issue, but now I see that because I committed to `zimolzak:main`, it auto-added that commit to this "one big pull request."

Hope it's OK to keep as "one big PR." I will edit the main PR description above.

**Review by EstherPlomp — APPROVED** [review]
Looks perfect! Thanks again for spotting this and for fixing it as well!

Apologies again for overlooking the PR :)

Cheers,
Esther

**Comment by zimolzak** [comment]
@EstherPlomp
Sorry, I can’t tell—do you mean for _me_ to merge?

I didn’t know I could do that. I don’t think I have “collaborator” permissions on this repo.

Thank you for your help with all of this!

**Comment by EstherPlomp** [comment]
Yes - we normally expect people to merge their own PRs - but I did not take into account that you weren't added to the repository yet because you already contributed to it before! 

I don't think that I can add you to the repository, so I'll tag @malvikasharan to see if she can add you. Hopefully she's not on leave yet!

**Comment by KirstieJane** [comment]
I've added you @zimolzak! 

Merge away! 🎉

Thank you for reviewing @EstherPlomp!

**Pull request merged**
