### PR TITLE
Add proposals, reports and other official submissions from 2022/2023

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

Adding proposals submitted in 2023

### List of changes proposed in this PR (pull-request)

* Add missing proposals
* Organise files that maybe in other folders

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
Posting this here for Ale and Anne to archive reports on Github: https://docs.google.com/document/d/1_-oSR55jaK0nJc6R25qBt9rxW_-XXN0WFgI98iATEbQ/edit

**Comment by malvikasharan** [comment]
Setting a deadline for this 1 April 2024.

**Comment by AlexandraAAJ** [comment]
2023 Report added, thanks

**Comment by malvikasharan** [comment]
Thank you Ale. @aleesteele can you please approve and merge this?

**Review by aleesteele — APPROVED** [review]

**Comment by aleesteele** [comment]
Merging this for now - and will add the other proposals as PRs 😄

**Pull request merged**
