### PR TITLE
Domain migration banner

### PR DESCRIPTION
**Pull request by JimMadge**
### Summary

Adds a banner explaining the domain migration to the top of any book page.
Part of #3266.
Don't merge until the new domain is confirmed and purchased.

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by JimMadge** [comment]
Still not quite ready yet. The banner says the new URL can be used "now", so this should go in once the DNS/custom domain is configured.

**Review by da5nsy — APPROVED** [review]
LGTM!
Is it worth merging a version of this now (that just has the first part of the statement)?

**Review by bsipocz — APPROVED** [review]
Sounds good, and should be good to go once the DNS is configed

**Review by AlexandraAAJ — APPROVED** [review]
Looks good to me.

**Pull request merged**
