### PR TITLE
Minor typos corrected in the data hazard workshop case study - possible to move this under online events chapter

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

* Minor typos fixed and corrected a 'note' box formatting

### List of changes proposed in this PR (pull-request)

* A case study under data hazard chapter may include a repository that uses data hazard label so the readers can refer to that and learn how they can structure their repo to include labels
* While reading this, I thought that the chapter fits as a case study for organising online events thoughfully, and can potentially be moved - would love to hear what @CeilidhWelsh and @Susana465 think

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok - in terms of typos corrected?
- [ ] Maybe discussion on moving this chapter can happen here and if agreed, edit to move the file can also take place here - or moved to an issue/new PR

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@Susana465 @CeilidhWelsh can I please draw your attention to this PR. 🙏

**Comment by Susana465** [comment]
Briefly discussed with @aleesteele @CeilidhWelsh - currently no time to address but have not forgotten and will tackle soon.

**Review by da5nsy — APPROVED** [review]
Reviewing spelling and grammar

**Review by aleesteele — APPROVED** [review]
Flagging these - the small changes look good to me 👍

**Review by bsipocz — APPROVED** [review]
Going ahead and merge this PR as there is no reason to hold up these minor fixes while the bigger picture is being decided.

**Pull request merged**
