### PR TITLE
Create Newsletter_40_Feb2023.md

### PR DESCRIPTION
**Pull request by AlexandraAAJ**
I'm creating the folder but the content needs to be added later. I can't find the md. file.
@aleesteele, can you help me?

### CODE REVIEW

**Comment by malvikasharan** [comment]
Missing draft content.

**Comment by aleesteele** [comment]
Draft content is here: https://hackmd.io/7lnnpIhCQi2fBy83_oTccQ?both

**Review by kallewesterling — APPROVED** [review]
I added in the content from the link above @AlexandraAAJ, so this should be ready for merge, if you want :)

**Comment by kallewesterling** [comment]
FYI @AlexandraAAJ - this was closed without merging. Not sure if that was the intention.

**Comment by AlexandraAAJ** [comment]
Noooo, any idea why it did not merged? I guess I have to open it again?

**Comment by kallewesterling** [comment]
@sgibson91 Do you have any idea why the deploys are failing here now? Or what to do to re-trigger the workflows? :/

**Comment by sgibson91** [comment]
@kallewesterling It's probably out of date with main. This is a very old PR, pre-move to the org. I'd use the "Update branch" button underneath the GitHub Actions to come up-to-date with main, that'll also retrigger the deployment and see if it passes.

**Comment by kallewesterling** [comment]
Thanks @sgibson91 -- trying that!

**Comment by kallewesterling** [comment]
✅ @AlexandraAAJ !!

**Pull request merged**
